"""What the bundled Python payload keeps, and how big it is allowed to get.

Spike R2 measured a relocatable CPython 3.14 at 68 MB unpacked and 355 MB
once requirements.lock is installed. Most of that is removable: 203 MB is the
claude-agent-sdk's own bundled `claude`, which agent_cli.py now bypasses in
favour of the one on PATH, and a large share is __pycache__ regenerated on
first import anyway.

The rules match whole PATH SEGMENTS, never substrings. A substring rule for
"test" also prunes pytest_asyncio; one for "pip" also prunes pipeline. Both
would break the backend at startup, in a build, with a traceback pointing at
an import rather than at this file.
"""
from __future__ import annotations

# Whole directory names to drop wherever they appear in the payload.
PRUNE_SEGMENTS: tuple[str, ...] = (
    "__pycache__",     # regenerated on first import
    "_bundled",        # the SDK's own 203 MB claude; agent_cli.py bypasses it
    "pip",             # nothing installs at runtime
    "setuptools",
    "pkg_resources",
    "tests",
    "test",
    "idlelib",         # the stdlib's Tk IDE
    "tkinter",         # no GUI toolkit is used; the app's UI is the renderer
    "lib2to3",
)

# Measured 81.2 MB on 2026-09-06 (from 321.3 MB untrimmed). ~10% headroom.
# A gate, not a guess: it exists so a dependency that quietly reintroduces a
# large payload fails the build instead of shipping.
#
# WHICH size this is, because the distinction bit once already: it is the size
# IMMEDIATELY AFTER the prune, which is what build-python.py checks and what
# ends up in the .dmg. It is NOT the size the payload has once it has been
# RUN. `__pycache__` is pruned and then regenerated by the first import, so a
# payload that has executed anything measures roughly 11 MB more (92.4 MB when
# measured after the import probe). Re-measuring a used payload and comparing
# it to this number will look like a breach that is not one -- rebuild with
# --clean before you conclude anything.
MAX_PAYLOAD_BYTES: int = 90 * 1024 * 1024


def should_prune(rel: str) -> bool:
    """Whether a payload-relative path should be dropped.

    `rel` is compared segment by segment, so "pytest_asyncio" survives a
    "test" rule and "pipeline" survives a "pip" rule.
    """
    return any(seg in PRUNE_SEGMENTS for seg in rel.split("/"))


def within_budget(total: int) -> bool:
    return total <= MAX_PAYLOAD_BYTES


def human(total: int) -> str:
    return f"{total / (1024 * 1024):.1f} MB"
